name: Update Repository

on:
  push:
    paths:
      - 'repository.nigel1992/addons/*/*'
      - '!repository.nigel1992/addons/*/[0-9]*'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Generate repository files
        run: |
          cd repository.nigel1992
          python generate_repo.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add only addon-specific changes, excluding version folders
          git add repository.nigel1992/addons/*/*
          git add --force repository.nigel1992/addons/*/resources/**
          # Ensure the main XML and necessary addon files are added
          git add repository.nigel1992/addons/addons.xml
          git add repository.nigel1992/addons/addons.xml.md5
          git commit -m "Auto-update addon files" || echo "No changes to commit"
          git push
