name: Update Repository

on:
  push:
    paths:
      - 'repository.nigel1992/addons/**'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Generate repository files
        run: |
          cd repository.nigel1992
          python generate_repo.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add all changes in the addons directory (including zip files and version directories)
          git add repository.nigel1992/addons/
          # Ensure the main XML files are added (if they weren't captured above)
          git add repository.nigel1992/addons/addons.xml
          git add repository.nigel1992/addons/addons.xml.md5
          git commit -m "Auto-update repository files" || echo "No changes to commit"
          git push 
